name: simple_file_downloader_dart
description: a simple file downloader by dio, support resume  from breakpoint
version: 1.0.0
repository: https://github.com/hss01248/simple_file_downloader_dart

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  # dio_http_formatter: ^2.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
